name: Build and Deploy SubWatch.API
env:
  OUTPUT_PATH: ${{ github.workspace }}/.ouput

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup .NET 6
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x
     - name: Restore dependencies
       run: dotnet restore
       working-directory: './SubWatch/*'
     - name: Build
       run: dotnet build --no-restore
       working-directory: './SubWatch/*'
     - name: Test
       run: dotnet test --no-build --verbosity normal
       working-directory: './SubWatch/*'
     - name: Publish Functions
       run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
       working-directory: './SubWatch/*'
     - name: Package Functions
       uses: actions/upload-artifact@v1
       with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}
  
  deploy:
    runs-on: ubuntu_latest
    needs: [build]
    env:
      FUNC_APP_NAME: fasubwatchapi
    steps:
     - name: Download function
       uses: actions/download-artifact@v1
       with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}
    
     - name: Login via Azure CLI
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
     - name: Deploy SubWatch.API Function
       uses: Azure/functions-action@v1
       with:
        app-name: ${{ env.FUNC_APP_NAME }}
        package: ${{ env.OUTPUT_PATH }}
      
  
